version: '2'
services:
    testangular4-app:
        image: testangular4
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testangular4-postgresql:5432/testangular4
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testangular4-postgresql:
        extends:
            file: postgresql.yml
            service: testangular4-postgresql
