version: '2'
services:
    testangular4-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/testangular4/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=testangular4
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
